### ISSUE TITLE
when loading a new dataset with an array selected, throws an Exception

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray-editor#234]
Happens whether we open via open data or open recent data, or open example dataset. Maybe "New" too?

It tries uses the name of the array selected in the old session and tries to open that in the new Session, which fails most of the time.

```python
Traceback (most recent call last):
  File "[...]\larray_editor\editor.py", line 745, in on_selection_changed
    array = self.data[name]
  File "[...]\larray\core\session.py", line 268, in __getitem__
    return self._objects[key]
KeyError: 'f'
```

**Comment by gdementen** [comment]
Cannot reproduce in any of my "almost ready" branches. I guess this was only an artefact of a WIP branch. Strange.
