### ISSUE TITLE
Plots via the console are broken

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray-editor#278]
Plots via Ctrl-P work fine, but the plot commands in the console are not displayed:

```python
>>> arr = ndtest((3, 4))
>>> arr.plot()
```

I suppose this is due to a matplotlib update. Sigh... 

When running from within a script, we see the traceback:
```python
Traceback (most recent call last):
  File "c:\users\gdm\devel\larray-editor\larray_editor\editor.py", line 737, in ipython_cell_executed
    show_figure(self, first_output.figure, last_input)
  File "c:\users\gdm\devel\larray-editor\larray_editor\utils.py", line 302, in show_figure
    figure.canvas.manager.window is not None):
AttributeError: 'FigureManagerBase' object has no attribute 'window'
```

**Comment by gdementen** [comment]
Just when I thought I had found the most obscure bug of the year with #277. This one beats it hands down. The culprit seems to be an update to **_xlwings_**. I still have no idea how this can possibly have an impact on matplotlib structures, but with xlwings 0.24.x several of my environments work while with xlwings 0.31.4, they don't. I am curious to know what the **** is actually happening.

**Comment by gdementen** [comment]
xlwings 0.29.1 works too

**Comment by gdementen** [comment]
Found the culprit. xlwings 0.31.4 added this code:

```python
import matplotlib as mpl
import matplotlib.figure  # noqa: F401
import matplotlib.pyplot as plt

# https://matplotlib.org/stable/users/explain/figure/backends.html#static-backends
# This prevents "Starting a Matplotlib GUI outside of the main thread will likely
# fail." with xlwings Server
mpl.use("agg")
```

See: https://github.com/xlwings/xlwings/pull/2445

I guess we will need to set an explicit backend ourselves. Unsure it should be done before or after importing xlwings though.
