### ISSUE TITLE
filtering up to the point you would get a scalar fails

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray-editor#71]
```python
Traceback (most recent call last):
  File "c:\users\gdm\devel\larray-editor\larray_editor\arraywidget.py", line 919, in filter_changed
    filtered = self.data_adapter.change_filter(axis, checked_items)
  File "c:\users\gdm\devel\larray-editor\larray_editor\arrayadapter.py", line 212, in change_filter
    self.update_filtered_data()
  File "c:\users\gdm\devel\larray-editor\larray_editor\arrayadapter.py", line 105, in update_filtered_data
    if len(self.filtered_data) == 0:
  File "c:\users\gdm\devel\larray\larray\core\array.py", line 6014, in __len__
    return len(self.data)
TypeError: len() of unsized object

```

**Comment by alixdamman** [comment]
The problem come from `aslarray(scalar)` which, in this case returns `Larray(scalar)` which executes 
`self.data = np.asarray(scalar)` which returns a Numpy ndarray with no length.
